### Params to change between exps:
exp_name: 'exp_matching_dot_no_resnet'
loss_path: 'cfg/loss/loss_matching_dot.yml'
is_pheno: False
###

### change these two running bridges vs local
# images and batch size
images_dir: &images_dir '/ocean/projects/agr240003p/hfreeman/t_ro/labels/selected_images/images'
#images_dir: &images_dir 'labelling/selected_images/images'
#batch_size: &batch_size 32
batch_size: &batch_size 32
###

full_cloud_dir: &full_cloud_dir 'labelling/full_point_clouds'

# data and logging
anno_root: &anno_root 'datasets/v1_bak_working_data'
checkpoint_dir: 'lightning_logs'
image_size: &image_size 128
#vis_encoder_type: &vis_encoder_type 'resnet-18'
vis_encoder_type: &vis_encoder_type 'zero'
pos_encoder_type: &pos_encoder_type 'harmonic'

# dataset confg
max_fruitlets: &max_fruitlets 8

# checkpoint metrics
checkpoint_metrics:
    metric_type: 'f1' #'val_loss'
    is_min: True

model_params:
  d_model: 512
  image_size: *image_size

  vis_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *vis_encoder_type

  pos_encoder_args:
    temperature: 10000
    orig_resolution: 0.02
    pos_encoder_type: *pos_encoder_type

  trans_encoder_args:
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    normalize_before: True
    num_layers: 4

train_params:
  num_epochs: 500
  lr: 1e-4
  weight_decay: null # 1e-5

  #scheduler: null
  scheduler:
    type: 'lr_step'
    gamma: 0.90
    train_step: 20

    # type: 'warmup_cosine'
    # warmup_epochs: 2
    # max_epochs: 40

  augment: 
    bright_pct: 0.5
    rotate_pct: 0.0
    drop_cloud_pct: 0.9 # want more now
    drop_seg_pct: 0.9 # no effect without pos
    crop_pct: 0.9
    drop_fruitlet_pct: 0.4 # want more now

  anno_root: *anno_root
  anno_subdir: 'train'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type

  max_fruitlets: *max_fruitlets

  is_test: False

val_params:
  augment: null

  anno_root: *anno_root
  anno_subdir: 'val'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type

  max_fruitlets: *max_fruitlets

  is_test: False

test_params:
  augment: null

  anno_root: *anno_root
  anno_subdir: 'test'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type

  max_fruitlets: *max_fruitlets

  is_test: True

  full_cloud_dir: *full_cloud_dir
