### Params to change between exps:
exp_name: 'contrastive_l2_overfit_debug'
loss_path: 'cfg/loss/loss_contrastive_l2.yml'
###

### change these two running bridges vs local
# images and batch size
#images_dir: &images_dir '/ocean/projects/agr240003p/hfreeman/t_ro/labels/selected_images/images'
images_dir: &images_dir 'labelling/selected_images/images'
#batch_size: &batch_size 32
batch_size: &batch_size 32
###

# data and logging
anno_root: &anno_root 'datasets'
cache: &cache True
checkpoint_dir: 'lightning_logs'
image_size: &image_size 128
vis_encoder_type: &vis_encoder_type 'resnet-18'

# dataset confg
max_fruitlets: &max_fruitlets 8
min_fruitlets_per_im: &min_fruitlets_per_im 3
min_fruitlet_matches: &min_fruitlet_matches 2

# checkpoint metrics
checkpoint_metrics:
    metric_type: 'val_loss'
    is_min: True

model_params:
  d_model: 256
  image_size: *image_size

  vis_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *vis_encoder_type

  pos_encoder_args:
    temperature: 10000
    orig_resolution: 0.002

  trans_encoder_args:
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.0
    normalize_before: True
    num_layers: 5

train_params:
  num_epochs: 200
  lr: 1e-4
  weight_decay: 1e-5

  #scheduler: null
  scheduler:
    type: 'lr_step'
    gamma: 0.95
    train_step: 50

    # type: 'warmup_cosine'
    # warmup_epochs: 2
    # max_epochs: 40

  augment: 
    bright_pct: 0.5
    rotate_pct: 0.0
    drop_cloud_pct: 0.6
    drop_seg_pct: 0.2
    crop_pct: 0.9
    drop_fruitlet_pct: 0.2

  anno_root: *anno_root
  anno_subdir: 'mini'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache

  max_fruitlets: *max_fruitlets
  min_fruitlets_per_im: *min_fruitlets_per_im
  min_fruitlet_matches: *min_fruitlet_matches

  is_test: False

val_params:
  augment: null

  anno_root: *anno_root
  anno_subdir: 'mini'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache

  max_fruitlets: *max_fruitlets
  min_fruitlets_per_im: *min_fruitlets_per_im
  min_fruitlet_matches: *min_fruitlet_matches

  is_test: False

test_params:
  augment: null

  anno_root: *anno_root
  anno_subdir: 'mini'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache

  max_fruitlets: *max_fruitlets
  min_fruitlets_per_im: *min_fruitlets_per_im
  min_fruitlet_matches: *min_fruitlet_matches

  is_test: True
