### Params to change between exps:
exp_name: 'pheno_overfit'
loss_path: 'cfg/loss/loss_contrastive_l2.yml'
# loss_path: 'cfg/loss/loss_matching.yml'
is_pheno: True
###

### change these two running bridges vs local
#batch size
#batch_size: &batch_size 32
batch_size: &batch_size 32
###

# data and logging
anno_root: &anno_root 'datasets/pheno'
pheno_type: &pheno_type 'tomato'
checkpoint_dir: 'lightning_logs'
vis_encoder_type: &vis_encoder_type 'pheno'
pos_encoder_type: &pos_encoder_type 'zero'

# dataset confg
max_comps: &max_comps 42
day_lim: &day_lim 5

# checkpoint metrics
checkpoint_metrics:
    metric_type: 'val_loss'
    is_min: True

model_params:
  d_model: 512

  image_size: null

  vis_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *vis_encoder_type

  pos_encoder_args:
    temperature: 10000
    orig_resolution: 80
    pos_encoder_type: *pos_encoder_type

  trans_encoder_args:
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    normalize_before: True
    num_layers: 4

train_params:
  num_epochs: 10000
  lr: 1e-4
  weight_decay: null #1e-5

  #scheduler: null
  scheduler:
    type: 'lr_step'
    gamma: 0.95
    train_step: 100

    # type: 'warmup_cosine'
    # warmup_epochs: 2
    # max_epochs: 40

  augment: 
    rotate_pct: 1.0
    drop_pct: 1.0

  # augment: null

  anno_root: *anno_root
  pheno_type: *pheno_type
  anno_subdir: 'train'

  encoder_type: *vis_encoder_type

  max_comps: *max_comps
  day_lim: *day_lim

  is_test: False

val_params:
  augment: null

  anno_root: *anno_root
  pheno_type: *pheno_type
  anno_subdir: 'test'

  encoder_type: *vis_encoder_type

  max_comps: *max_comps
  day_lim: *day_lim

  is_test: False

test_params:
  augment: null

  anno_root: *anno_root
  pheno_type: *pheno_type
  anno_subdir: 'test'

  encoder_type: *vis_encoder_type

  max_comps: *max_comps
  day_lim: *day_lim

  is_test: True
