exp_name: 'overfit_exp'

anno_root: &anno_root 'datasets'
images_dir: &images_dir '/home/frc-ag-3/harry_ws/fruitlet_2023/labelling/inhand/tro_final/selected_images/images'
cache: &cache True
checkpoint_dir: 'lightning_logs'

image_size: &image_size 128
vis_encoder_type: &vis_encoder_type 'resnet-34'
pos_encoder_type: &pos_encoder_type 'resnet-34'

match_thresh: &match_thresh 0.5

loss_params: &loss_params
  dist_type: 'l2'
  alpha: 1.0

model_params:
  d_model: 256
  image_size: *image_size

  vis_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *vis_encoder_type

  pos_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *pos_encoder_type

  trans_encoder_args:
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.0
    num_layers: 5

train_params:
  num_epochs: 100
  batch_size: 8
  lr: 1e-5
  weight_decay: null
  augment: True

  anno_root: *anno_root
  anno_subdir: 'mini_train'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh

val_params:
  batch_size: 8
  augment: False

  anno_root: *anno_root
  anno_subdir: 'mini_val'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh

test_params:
  batch_size: 8
  augment: False

  checkpoint_metrics:
    metric_type: 'val_loss'
    is_min: True

  anno_root: *anno_root
  anno_subdir: 'mini_val'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh