exp_name: 'exp_full_2_layer'

anno_root: &anno_root 'datasets'
cache: &cache True
checkpoint_dir: 'lightning_logs'

# change these two running bridges vs local
images_dir: &images_dir '/ocean/projects/agr240003p/hfreeman/t_ro/labels/selected_images/images'
#images_dir: &images_dir '/home/frc-ag-3/harry_ws/fruitlet_2023/labelling/inhand/tro_final/selected_images/images'
batch_size: &batch_size 32
#batch_size: &batch_size 8

image_size: &image_size 128
vis_encoder_type: &vis_encoder_type 'resnet-18'
pos_encoder_type: &pos_encoder_type 'resnet-18'

match_thresh: &match_thresh 0.5

loss_params: &loss_params
  dist_type: 'l2'
  alpha: 1.0

model_params:
  d_model: 256
  image_size: *image_size

  vis_encoder_args:
    pretrained: True
    use_cls: True
    encoder_type: *vis_encoder_type

  pos_encoder_args:
    temperature: 10000
    orig_resolution: 0.002

  trans_encoder_args:
    nhead: 8
    dim_feedforward: 512
    dropout: 0.0
    num_layers: 2

train_params:
  num_epochs: 200
  batch_size: *batch_size
  lr: 1e-4
  weight_decay: 1e-4
  gamma: 0.95
  train_step: 50
  augment: True

  anno_root: *anno_root
  anno_subdir: 'train'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh

val_params:
  batch_size: *batch_size
  augment: False

  anno_root: *anno_root
  anno_subdir: 'val'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh

test_params:
  batch_size: *batch_size
  augment: False

  checkpoint_metrics:
    metric_type: 'f1'
    is_min: False

  anno_root: *anno_root
  anno_subdir: 'train'
  images_dir: *images_dir
  image_size: *image_size
  encoder_type: *vis_encoder_type
  cache: *cache
  match_thresh: *match_thresh

  use_icp: False